# Generated by Django 4.1.13 on 2026-08-10 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAssistantConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("friendly", "Friendly"),
                            ("humorous", "Humorous"),
                        ],
                        default="friendly",
                        max_length=50,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are a helpful assistant responding to messages in a chat. Keep responses concise and natural."
                    ),
                ),
                ("max_tokens", models.IntegerField(default=150)),
                ("temperature", models.FloatField(default=0.7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("suggested_response", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected by user"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("user_edited", models.BooleanField(default=False)),
                ("user_edit_reason", models.TextField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="ai_assistant.aiassistantconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
