# Generated by Django 4.1.13 on 2026-08-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_assistant", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airesponse",
            name="sent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_sent_from",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="airesponse",
            name="trigger_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_responses",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="aiassistantconfig",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_configs",
                to="chat.chatroom",
            ),
        ),
    ]
