# Generated by Django 4.1.13 on 2026-08-10 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_assistant", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiassistantconfig",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(
                fields=["config", "-created_at"], name="ai_assistan_config__8fbc79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(fields=["status"], name="ai_assistan_status_9dca6c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="aiassistantconfig",
            unique_together={("user", "chat_room")},
        ),
    ]
